export interface Country {
  class: string;
  prefix: string;
  keyOnEnglish: string;
  key: string;
  code: string;
}

export const countries: Country[] = [
  {
    class: "flag flag-16 flag-af",
    prefix: "+93",
    keyOnEnglish: "Afghanistan",
    key: "Afganistán",
    code: "AF",
  },
  {
    class: "flag flag-16 flag-al",
    prefix: "+355",
    keyOnEnglish: "Albania",
    key: "Albania",
    code: "AL",
  },
  {
    class: "flag flag-16 flag-de",
    prefix: "+49",
    keyOnEnglish: "Germany",
    key: "Alemania",
    code: "DE",
  },
  {
    class: "flag flag-16 flag-ad",
    prefix: "+376",
    keyOnEnglish: "Andorra",
    key: "Andorra",
    code: "AD",
  },
  {
    class: "flag flag-16 flag-ao",
    prefix: "+244",
    keyOnEnglish: "Angola",
    key: "Angola",
    code: "AO",
  },
  {
    class: "flag flag-16 flag-ag",
    prefix: "+1",
    keyOnEnglish: "Antigua and Barbuda",
    key: "Antigua y Barbuda",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-sa",
    prefix: "+966",
    keyOnEnglish: "Saudi Arabia",
    key: "Arabia Saudita",
    code: "SA",
  },
  {
    class: "flag flag-16 flag-dz",
    prefix: "+213",
    keyOnEnglish: "Algeria",
    key: "Argelia",
    code: "DZ",
  },
  {
    class: "flag flag-16 flag-ar",
    prefix: "+54",
    keyOnEnglish: "Argentina",
    key: "Argentina",
    code: "AR",
  },
  {
    class: "flag flag-16 flag-am",
    prefix: "+374",
    keyOnEnglish: "Armenia",
    key: "Armenia",
    code: "AM",
  },
  {
    class: "flag flag-16 flag-au",
    prefix: "+61",
    keyOnEnglish: "Australia",
    key: "Australia",
    code: "AU",
  },
  {
    class: "flag flag-16 flag-at",
    prefix: "+43",
    keyOnEnglish: "Austria",
    key: "Austria",
    code: "AT",
  },
  {
    class: "flag flag-16 flag-az",
    prefix: "+994",
    keyOnEnglish: "Azerbaijan",
    key: "Azerbaiyán",
    code: "AZ",
  },
  {
    class: "flag flag-16 flag-bs",
    prefix: "+1",
    keyOnEnglish: "Bahamas",
    key: "Bahamas",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-bd",
    prefix: "+880",
    keyOnEnglish: "Bangladesh",
    key: "Bangladés",
    code: "BD",
  },
  {
    class: "flag flag-16 flag-bb",
    prefix: "+1",
    keyOnEnglish: "Barbados",
    key: "Barbados",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-bh",
    prefix: "+973",
    keyOnEnglish: "Bahrain",
    key: "Baréin",
    code: "BH",
  },
  {
    class: "flag flag-16 flag-be",
    prefix: "+32",
    keyOnEnglish: "Belgium",
    key: "Bélgica",
    code: "BE",
  },
  {
    class: "flag flag-16 flag-bz",
    prefix: "+501",
    keyOnEnglish: "Belize",
    key: "Belice",
    code: "BZ",
  },
  {
    class: "flag flag-16 flag-bj",
    prefix: "+229",
    keyOnEnglish: "Benin",
    key: "Benín",
    code: "BJ",
  },
  {
    class: "flag flag-16 flag-by",
    prefix: "+375",
    keyOnEnglish: "Belarus",
    key: "Bielorrusia",
    code: "BY",
  },
  {
    class: "flag flag-16 flag-bo",
    prefix: "+591",
    keyOnEnglish: "Bolivia",
    key: "Bolivia",
    code: "BO",
  },
  {
    class: "flag flag-16 flag-ba",
    prefix: "+387",
    keyOnEnglish: "Bosnia and Herzegovina",
    key: "Bosnia y Herzegovina",
    code: "BA",
  },
  {
    class: "flag flag-16 flag-bw",
    prefix: "+267",
    keyOnEnglish: "Botswana",
    key: "Botsuana",
    code: "BW",
  },
  {
    class: "flag flag-16 flag-br",
    prefix: "+55",
    keyOnEnglish: "Brazil",
    key: "Brasil",
    code: "BR",
  },
  {
    class: "flag flag-16 flag-bn",
    prefix: "+673",
    keyOnEnglish: "Brunei",
    key: "Brunéi",
    code: "BN",
  },
  {
    class: "flag flag-16 flag-bg",
    prefix: "+359",
    keyOnEnglish: "Bulgaria",
    key: "Bulgaria",
    code: "BG",
  },
  {
    class: "flag flag-16 flag-bf",
    prefix: "+226",
    keyOnEnglish: "Burkina Faso",
    key: "Burkina Faso",
    code: "BF",
  },
  {
    class: "flag flag-16 flag-bi",
    prefix: "+257",
    keyOnEnglish: "Burundi",
    key: "Burundi",
    code: "BI",
  },
  {
    class: "flag flag-16 flag-bt",
    prefix: "+975",
    keyOnEnglish: "Bhutan",
    key: "Bután",
    code: "BT",
  },
  {
    class: "flag flag-16 flag-cv",
    prefix: "+238",
    keyOnEnglish: "Cape Verde",
    key: "Cabo Verde",
    code: "CV",
  },
  {
    class: "flag flag-16 flag-kh",
    prefix: "+855",
    keyOnEnglish: "Cambodia",
    key: "Camboya",
    code: "KH",
  },
  {
    class: "flag flag-16 flag-cm",
    prefix: "+237",
    keyOnEnglish: "Cameroon",
    key: "Camerún",
    code: "CM",
  },
  {
    class: "flag flag-16 flag-ca",
    prefix: "+1",
    keyOnEnglish: "Canada",
    key: "Canadá",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-qa",
    prefix: "+974",
    keyOnEnglish: "Taste",
    key: "Catar",
    code: "QA",
  },
  {
    class: "flag flag-16 flag-td",
    prefix: "+235",
    keyOnEnglish: "Chad",
    key: "Chad",
    code: "TD",
  },
  {
    class: "flag flag-16 flag-cl",
    prefix: "+56",
    keyOnEnglish: "Chile",
    key: "Chile",
    code: "CL",
  },
  {
    class: "flag flag-16 flag-cn",
    prefix: "+86",
    keyOnEnglish: "China",
    key: "China",
    code: "CN",
  },
  {
    class: "flag flag-16 flag-cy",
    prefix: "+357",
    keyOnEnglish: "Cyprus",
    key: "Chipre",
    code: "not",
  },
  {
    class: "flag flag-16 flag-co",
    prefix: "+57",
    keyOnEnglish: "Colombia",
    key: "Colombia",
    code: "CO",
  },
  {
    class: "flag flag-16 flag-km",
    prefix: "+269",
    keyOnEnglish: "Comoros",
    key: "Comoras",
    code: "KM",
  },
  {
    class: "flag flag-16 flag-kp",
    prefix: "+850",
    keyOnEnglish: "North Korea",
    key: "Corea del Norte",
    code: "KP",
  },
  {
    class: "flag flag-16 flag-kr",
    prefix: "+82",
    keyOnEnglish: "South Korea",
    key: "Corea del Sur",
    code: "KR",
  },
  {
    class: "flag flag-16 flag-ci",
    prefix: "+225",
    keyOnEnglish: "Ivory Coast",
    key: "Costa de Marfil",
    code: "CI",
  },
  {
    class: "flag flag-16 flag-cr",
    prefix: "+506",
    keyOnEnglish: "Costa Rica",
    key: "Costa Rica",
    code: "CR",
  },
  {
    class: "flag flag-16 flag-hr",
    prefix: "+385",
    keyOnEnglish: "Croatia",
    key: "Croacia",
    code: "HR",
  },
  {
    class: "flag flag-16 flag-cu",
    prefix: "+53",
    keyOnEnglish: "Cuba",
    key: "Cuba",
    code: "CU",
  },
  {
    class: "flag flag-16 flag-dk",
    prefix: "+45",
    keyOnEnglish: "Denmark",
    key: "Dinamarca",
    code: "DK",
  },
  {
    class: "flag flag-16 flag-dm",
    prefix: "+1",
    keyOnEnglish: "Dominica",
    key: "Dominica",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-ec",
    prefix: "+593",
    keyOnEnglish: "Ecuador",
    key: "Ecuador",
    code: "EC",
  },
  {
    class: "flag flag-16 flag-eg",
    prefix: "+20",
    keyOnEnglish: "Egypt",
    key: "Egipto",
    code: "EG",
  },
  {
    class: "flag flag-16 flag-sv",
    prefix: "+503",
    keyOnEnglish: "El Salvador",
    key: "El Salvador",
    code: "SV",
  },
  {
    class: "flag flag-16 flag-ae",
    prefix: "+971",
    keyOnEnglish: "United Arab Emirates",
    key: "Emiratos Árabes Unidos",
    code: "AE",
  },
  {
    class: "flag flag-16 flag-er",
    prefix: "+291",
    keyOnEnglish: "Eritrea",
    key: "Eritrea",
    code: "ER",
  },
  {
    class: "flag flag-16 flag-sk",
    prefix: "+421",
    keyOnEnglish: "Slovakia",
    key: "Eslovaquia",
    code: "SK",
  },
  {
    class: "flag flag-16 flag-si",
    prefix: "+386",
    keyOnEnglish: "Slovenia",
    key: "Eslovenia",
    code: "SI",
  },
  {
    class: "flag flag-16 flag-es",
    prefix: "+34",
    keyOnEnglish: "Spain",
    key: "España",
    code: "ES",
  },
  {
    class: "flag flag-16 flag-us",
    prefix: "+1",
    keyOnEnglish: "United States",
    key: "Estados Unidos",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-ee",
    prefix: "+372",
    keyOnEnglish: "Estonia",
    key: "Estonia",
    code: "EE",
  },
  {
    class: "flag flag-16 flag-et",
    prefix: "+251",
    keyOnEnglish: "Ethiopia",
    key: "Etiopía",
    code: "ET",
  },
  {
    class: "flag flag-16 flag-ph",
    prefix: "+63",
    keyOnEnglish: "Philippines",
    key: "Filipinas",
    code: "PH",
  },
  {
    class: "flag flag-16 flag-fi",
    prefix: "+358",
    keyOnEnglish: "Finland",
    key: "Finlandia",
    code: "FI",
  },
  {
    class: "flag flag-16 flag-fj",
    prefix: "+679",
    keyOnEnglish: "Fiji",
    key: "Fiyi",
    code: "FJ",
  },
  {
    class: "flag flag-16 flag-fr",
    prefix: "+33",
    keyOnEnglish: "France",
    key: "Francia",
    code: "FR",
  },
  {
    class: "flag flag-16 flag-ga",
    prefix: "+241",
    keyOnEnglish: "Gabon",
    key: "Gabón",
    code: "GA",
  },
  {
    class: "flag flag-16 flag-gm",
    prefix: "+220",
    keyOnEnglish: "Gambia",
    key: "Gambia",
    code: "GM",
  },
  {
    class: "flag flag-16 flag-ge",
    prefix: "+995",
    keyOnEnglish: "Georgia",
    key: "Georgia",
    code: "GE",
  },
  {
    class: "flag flag-16 flag-gh",
    prefix: "+233",
    keyOnEnglish: "Ghana",
    key: "Ghana",
    code: "GH",
  },
  {
    class: "flag flag-16 flag-gd",
    prefix: "+1",
    keyOnEnglish: "Grenada",
    key: "Granada",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-gr",
    prefix: "+30",
    keyOnEnglish: "Greece",
    key: "Grecia",
    code: "GR",
  },
  {
    class: "flag flag-16 flag-gt",
    prefix: "+502",
    keyOnEnglish: "Guatemala",
    key: "Guatemala",
    code: "GT",
  },
  {
    class: "flag flag-16 flag-gn",
    prefix: "+224",
    keyOnEnglish: "Guinea",
    key: "Guinea",
    code: "GN",
  },
  {
    class: "flag flag-16 flag-gw",
    prefix: "+245",
    keyOnEnglish: "Guinea-Bissau",
    key: "Guinea-Bisáu",
    code: "GW",
  },
  {
    class: "flag flag-16 flag-gq",
    prefix: "+240",
    keyOnEnglish: "Equatorial Guinea",
    key: "Guinea Ecuatorial",
    code: "GQ",
  },
  {
    class: "flag flag-16 flag-gy",
    prefix: "+592",
    keyOnEnglish: "Guyana",
    key: "Guyana",
    code: "not",
  },
  {
    class: "flag flag-16 flag-ht",
    prefix: "+509",
    keyOnEnglish: "Haiti",
    key: "Haití",
    code: "HT",
  },
  {
    class: "flag flag-16 flag-hn",
    prefix: "+504",
    keyOnEnglish: "Honduras",
    key: "Honduras",
    code: "HN",
  },
  {
    class: "flag flag-16 flag-hu",
    prefix: "+36",
    keyOnEnglish: "Hungary",
    key: "Hungría",
    code: "HU",
  },
  {
    class: "flag flag-16 flag-in",
    prefix: "+91",
    keyOnEnglish: "India",
    key: "India",
    code: "IN",
  },
  {
    class: "flag flag-16 flag-id",
    prefix: "+62",
    keyOnEnglish: "Indonesia",
    key: "Indonesia",
    code: "ID",
  },
  {
    class: "flag flag-16 flag-iq",
    prefix: "+964",
    keyOnEnglish: "Iraq",
    key: "Irak",
    code: "IQ",
  },
  {
    class: "flag flag-16 flag-ir",
    prefix: "+98",
    keyOnEnglish: "Iran",
    key: "Irán",
    code: "IR",
  },
  {
    class: "flag flag-16 flag-ie",
    prefix: "+353",
    keyOnEnglish: "Ireland",
    key: "Irlanda",
    code: "IE",
  },
  {
    class: "flag flag-16 flag-is",
    prefix: "+354",
    keyOnEnglish: "Iceland",
    key: "Islandia",
    code: "IS",
  },
  {
    class: "flag flag-16 flag-mh",
    prefix: "+692",
    keyOnEnglish: "Marshall Islands",
    key: "Islas Marshall",
    code: "MH",
  },
  {
    class: "flag flag-16 flag-sb",
    prefix: "+677",
    keyOnEnglish: "Solomon Islands",
    key: "Islas Salomón",
    code: "SB",
  },
  {
    class: "flag flag-16 flag-il",
    prefix: "+972",
    keyOnEnglish: "Israel",
    key: "Israel",
    code: "IL",
  },
  {
    class: "flag flag-16 flag-it",
    prefix: "+39",
    keyOnEnglish: "Italy",
    key: "Italia",
    code: "IT",
  },
  {
    class: "flag flag-16 flag-jm",
    prefix: "+1",
    keyOnEnglish: "Jamaica",
    key: "Jamaica",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-jp",
    prefix: "+81",
    keyOnEnglish: "Japan",
    key: "Japón",
    code: "JP",
  },
  {
    class: "flag flag-16 flag-jo",
    prefix: "+962",
    keyOnEnglish: "Jordan",
    key: "Jordania",
    code: "JO",
  },
  {
    class: "flag flag-16 flag-kz",
    prefix: "+7",
    keyOnEnglish: "Kazakhstan",
    key: "Kazajistán",
    code: "KZ",
  },
  {
    class: "flag flag-16 flag-ke",
    prefix: "+254",
    keyOnEnglish: "Kenya",
    key: "Kenia",
    code: "KE",
  },
  {
    class: "flag flag-16 flag-kg",
    prefix: "+996",
    keyOnEnglish: "Kyrgyzstan",
    key: "Kirguistán",
    code: "KG",
  },
  {
    class: "flag flag-16 flag-ki",
    prefix: "+686",
    keyOnEnglish: "Kiribati",
    key: "Kiribati",
    code: "KI",
  },
  {
    class: "flag flag-16 flag-kw",
    prefix: "+965",
    keyOnEnglish: "Kuwait",
    key: "Kuwait",
    code: "KW",
  },
  {
    class: "flag flag-16 flag-la",
    prefix: "+856",
    keyOnEnglish: "Laos",
    key: "Laos",
    code: "LA",
  },
  {
    class: "flag flag-16 flag-ls",
    prefix: "+266",
    keyOnEnglish: "Lesotho",
    key: "Lesoto",
    code: "LS",
  },
  {
    class: "flag flag-16 flag-lv",
    prefix: "+371",
    keyOnEnglish: "Latvia",
    key: "Letonia",
    code: "LV",
  },
  {
    class: "flag flag-16 flag-lb",
    prefix: "+961",
    keyOnEnglish: "Lebanon",
    key: "Líbano",
    code: "LB",
  },
  {
    class: "flag flag-16 flag-lr",
    prefix: "+231",
    keyOnEnglish: "Liberia",
    key: "Liberia",
    code: "LR",
  },
  {
    class: "flag flag-16 flag-ly",
    prefix: "+218",
    keyOnEnglish: "Libya",
    key: "Libia",
    code: "LY",
  },
  {
    class: "flag flag-16 flag-li",
    prefix: "+423",
    keyOnEnglish: "Liechtenstein",
    key: "Liechtenstein",
    code: "LI",
  },
  {
    class: "flag flag-16 flag-lt",
    prefix: "+370",
    keyOnEnglish: "Lithuania",
    key: "Lituania",
    code: "LT",
  },
  {
    class: "flag flag-16 flag-lu",
    prefix: "+352",
    keyOnEnglish: "Luxembourg",
    key: "Luxemburgo",
    code: "LU",
  },
  {
    class: "flag flag-16 flag-mk",
    prefix: "+389",
    keyOnEnglish: "North Macedonia",
    key: "Macedonia del Norte",
    code: "MK",
  },
  {
    class: "flag flag-16 flag-mg",
    prefix: "+261",
    keyOnEnglish: "Madagascar",
    key: "Madagascar",
    code: "MG",
  },
  {
    class: "flag flag-16 flag-my",
    prefix: "+60",
    keyOnEnglish: "Malaysia",
    key: "Malasia",
    code: "MY",
  },
  {
    class: "flag flag-16 flag-mw",
    prefix: "+265",
    keyOnEnglish: "Malawi",
    key: "Malaui",
    code: "MW",
  },
  {
    class: "flag flag-16 flag-mv",
    prefix: "+960",
    keyOnEnglish: "Maldives",
    key: "Maldivas",
    code: "MV",
  },
  {
    class: "flag flag-16 flag-ml",
    prefix: "+223",
    keyOnEnglish: "Mali",
    key: "Malí",
    code: "ML",
  },
  {
    class: "flag flag-16 flag-mt",
    prefix: "+356",
    keyOnEnglish: "Malt",
    key: "Malta",
    code: "MT",
  },
  {
    class: "flag flag-16 flag-ma",
    prefix: "+212",
    keyOnEnglish: "Morocco",
    key: "Marruecos",
    code: "MA",
  },
  {
    class: "flag flag-16 flag-mu",
    prefix: "+230",
    keyOnEnglish: "Mauricio",
    key: "Mauricio",
    code: "MU",
  },
  {
    class: "flag flag-16 flag-mr",
    prefix: "+222",
    keyOnEnglish: "Mauritania",
    key: "Mauritania",
    code: "MR",
  },
  {
    class: "flag flag-16 flag-mx",
    prefix: "+52",
    keyOnEnglish: "Mexico",
    key: "México",
    code: "MX",
  },
  {
    class: "flag flag-16 flag-fm",
    prefix: "+691",
    keyOnEnglish: "Micronesia",
    key: "Micronesia",
    code: "FM",
  },
  {
    class: "flag flag-16 flag-md",
    prefix: "+373",
    keyOnEnglish: "Moldova",
    key: "Moldavia",
    code: "MD",
  },
  {
    class: "flag flag-16 flag-mc",
    prefix: "+377",
    keyOnEnglish: "Monaco",
    key: "Mónaco",
    code: "MC",
  },
  {
    class: "flag flag-16 flag-mn",
    prefix: "+976",
    keyOnEnglish: "Mongolia",
    key: "Mongolia",
    code: "MN",
  },
  {
    class: "flag flag-16 flag-me",
    prefix: "+382",
    keyOnEnglish: "Montenegro",
    key: "Montenegro",
    code: "ME",
  },
  {
    class: "flag flag-16 flag-mz",
    prefix: "+258",
    keyOnEnglish: "Mozambique",
    key: "Mozambique",
    code: "MZ",
  },
  {
    class: "flag flag-16 flag-mm",
    prefix: "+95",
    keyOnEnglish: "Burma",
    key: "Birmania",
    code: "MM",
  },
  {
    class: "flag flag-16 flag-na",
    prefix: "+264",
    keyOnEnglish: "Namibia",
    key: "Namibia",
    code: "NA",
  },
  {
    class: "flag flag-16 flag-nr",
    prefix: "+674",
    keyOnEnglish: "Nauru",
    key: "Nauru",
    code: "NR",
  },
  {
    class: "flag flag-16 flag-np",
    prefix: "+977",
    keyOnEnglish: "Nepal",
    key: "Nepal",
    code: "NP",
  },
  {
    class: "flag flag-16 flag-ni",
    prefix: "+505",
    keyOnEnglish: "Nicaragua",
    key: "Nicaragua",
    code: "NI",
  },
  {
    class: "flag flag-16 flag-ne",
    prefix: "+227",
    keyOnEnglish: "Niger",
    key: "Níger",
    code: "NE",
  },
  {
    class: "flag flag-16 flag-ng",
    prefix: "+234",
    keyOnEnglish: "Nigeria",
    key: "Nigeria",
    code: "NG",
  },
  {
    class: "flag flag-16 flag-no",
    prefix: "+47",
    keyOnEnglish: "Norway",
    key: "Noruega",
    code: "NO",
  },
  {
    class: "flag flag-16 flag-nz",
    prefix: "+64",
    keyOnEnglish: "New Zealand",
    key: "Nueva Zelanda",
    code: "NZ",
  },
  {
    class: "flag flag-16 flag-om",
    prefix: "+968",
    keyOnEnglish: "Oman",
    key: "Omán",
    code: "OM",
  },
  {
    class: "flag flag-16 flag-nl",
    prefix: "+31",
    keyOnEnglish: "Netherlands",
    key: "Países Bajos",
    code: "NL",
  },
  {
    class: "flag flag-16 flag-pk",
    prefix: "+92",
    keyOnEnglish: "Pakistan",
    key: "Pakistán",
    code: "PK",
  },
  {
    class: "flag flag-16 flag-pw",
    prefix: "+680",
    keyOnEnglish: "Palau",
    key: "Palaos",
    code: "PW",
  },
  {
    class: "flag flag-16 flag-pa",
    prefix: "+507",
    keyOnEnglish: "Panama",
    key: "Panamá",
    code: "PA",
  },
  {
    class: "flag flag-16 flag-pg",
    prefix: "+675",
    keyOnEnglish: "Papua New Guinea",
    key: "Papúa Nueva Guinea",
    code: "PG",
  },
  {
    class: "flag flag-16 flag-py",
    prefix: "+595",
    keyOnEnglish: "Paraguay",
    key: "Paraguay",
    code: "GY",
  },
  {
    class: "flag flag-16 flag-pe",
    prefix: "+51",
    keyOnEnglish: "Peru",
    key: "Perú",
    code: "PE",
  },
  {
    class: "flag flag-16 flag- pl",
    prefix: "+48",
    keyOnEnglish: "Poland",
    key: "Polonia",
    code: "PL",
  },
  {
    class: "flag flag-16 flag-pt",
    prefix: "+351",
    keyOnEnglish: "Portugal",
    key: "Portugal",
    code: "PT",
  },
  {
    class: "flag flag-16 flag-gb",
    prefix: "+44",
    keyOnEnglish: "United Kingdom",
    key: "Reino Unido",
    code: "GG",
  },
  {
    class: "flag flag-16 flag-cf",
    prefix: "+236",
    keyOnEnglish: "Central African Republic",
    key: "República Centroafricana",
    code: "CF",
  },
  {
    class: "flag flag-16 flag-cz",
    prefix: "+420",
    keyOnEnglish: "Czech Republic",
    key: "República Checa",
    code: "CZ",
  },
  {
    class: "flag flag-16 flag-cg",
    prefix: "+242",
    keyOnEnglish: "Republic of Congo",
    key: "República del Congo",
    code: "CG",
  },
  {
    class: "flag flag-16 flag-cd",
    prefix: "+243",
    keyOnEnglish: "Democratic Republic of Congo",
    key: "República Democrática del Congo",
    code: "CD",
  },
  {
    class: "flag flag-16 flag-do ",
    prefix: "+1",
    keyOnEnglish: "Dominican Republic",
    key: "República Dominicana",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-rw",
    prefix: "+250",
    keyOnEnglish: "Rwanda",
    key: "Ruanda",
    code: "RW",
  },
  {
    class: "flag flag-16 flag-ro",
    prefix: "+40",
    keyOnEnglish: "Romania",
    key: "Rumania",
    code: "RO",
  },
  {
    class: "flag flag-16 flag-ru",
    prefix: "+7",
    keyOnEnglish: "Russia",
    key: "Rusia",
    code: "KZ",
  },
  {
    class: "flag flag-16 flag-ws",
    prefix: "+685",
    keyOnEnglish: "Samoa",
    key: "Samoa",
    code: "WS",
  },
  {
    class: "flag flag-16 flag-kn",
    prefix: "+1",
    keyOnEnglish: "Saint Kitts and Nevis",
    key: "San Cristóbal y Nieves",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-sm",
    prefix: "+378",
    keyOnEnglish: "San Marino",
    key: "San Marino",
    code: "SM",
  },
  {
    class: "flag flag-16 flag-vc",
    prefix: "+1",
    keyOnEnglish: "St.Vincent and the Grenadines",
    key: "San Vicente y las Granadinas",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-lc",
    prefix: "+1",
    keyOnEnglish: "St.Lucia",
    key: "Santa Lucía",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-st",
    prefix: "+239",
    keyOnEnglish: "Sao Tome and Principe",
    key: "Santo Tomé y Príncipe",
    code: "ST",
  },
  {
    class: "flag flag-16 flag-sn",
    prefix: "+221",
    keyOnEnglish: "Senegal",
    key: "Senegal",
    code: "SN",
  },
  {
    class: "flag flag-16 flag-rs",
    prefix: "+381",
    keyOnEnglish: "Serbia",
    key: "Serbia",
    code: "RS",
  },
  {
    class: "flag flag-16 flag-sc",
    prefix: "+248",
    keyOnEnglish: "Seychelles",
    key: "Seychelles",
    code: "SC",
  },
  {
    class: "flag flag-16 flag-sl",
    prefix: "+232",
    keyOnEnglish: "Sierra Leone",
    key: "Sierra Leona",
    code: "SL",
  },
  {
    class: "flag flag-16 flag-sg",
    prefix: "+65",
    keyOnEnglish: "Singapore",
    key: "Singapur",
    code: "SG",
  },
  {
    class: "flag flag-16 flag-sy",
    prefix: "+963",
    keyOnEnglish: "Syria",
    key: "Siria",
    code: "SY",
  },
  {
    class: "flag flag-16 flag-so",
    prefix: "+252",
    keyOnEnglish: "Somalia",
    key: "Somalia",
    code: "SO",
  },
  {
    class: "flag flag-16 flag-lk",
    prefix: "+94",
    keyOnEnglish: "Sri Lanka",
    key: "Sri Lanka",
    code: "LK",
  },
  {
    class: "flag flag-16 flag-sz",
    prefix: "+268",
    keyOnEnglish: "Swaziland",
    key: "Suazilandia",
    code: "SZ",
  },
  {
    class: "flag flag-16 flag-za",
    prefix: "+27",
    keyOnEnglish: "South Africa",
    key: "Sudáfrica",
    code: "ZA",
  },
  {
    class: "flag flag-16 flag-sd",
    prefix: "+249",
    keyOnEnglish: "Sudan",
    key: "Sudán",
    code: "SD",
  },
  {
    class: "flag flag-16 flag-ss",
    prefix: "+211",
    keyOnEnglish: "South Sudan",
    key: "Sudán del Sur",
    code: "SS",
  },
  {
    class: "flag flag-16 flag-se",
    prefix: "+46",
    keyOnEnglish: "Sweden",
    key: "Suecia",
    code: "SE",
  },
  {
    class: "flag flag-16 flag-ch",
    prefix: "+41",
    keyOnEnglish: "Switzerland",
    key: "Suiza",
    code: "CH",
  },
  {
    class: "flag flag-16 flag-sr",
    prefix: "+597",
    keyOnEnglish: "Surinam",
    key: "Surinam",
    code: "SR",
  },
  {
    class: "flag flag-16 flag-th",
    prefix: "+66",
    keyOnEnglish: "Thailand",
    key: "Tailandia",
    code: "TH",
  },
  {
    class: "flag flag-16 flag-tz",
    prefix: "+255",
    keyOnEnglish: "Tanzania",
    key: "Tanzania",
    code: "TZ",
  },
  {
    class: "flag flag-16 flag-tj",
    prefix: "+992",
    keyOnEnglish: "Tajikistan",
    key: "Tayikistán",
    code: "TJ",
  },
  {
    class: "flag flag-16 flag-tl",
    prefix: "+670",
    keyOnEnglish: "East Timor",
    key: "Timor Oriental",
    code: "TL",
  },
  {
    class: "flag flag-16 flag-tg",
    prefix: "+228",
    keyOnEnglish: "Togo",
    key: "Togo",
    code: "TG",
  },
  {
    class: "flag flag-16 flag-to",
    prefix: "+676",
    keyOnEnglish: "Tonga",
    key: "Tonga",
    code: "TO",
  },
  {
    class: "flag flag-16 flag-tt",
    prefix: "+1",
    keyOnEnglish: "Trinidad and Tobago",
    key: "Trinidad y Tobago",
    code: "CA",
  },
  {
    class: "flag flag-16 flag-tn",
    prefix: "+216",
    keyOnEnglish: "Tunisia",
    key: "Túnez",
    code: "TN",
  },
  {
    class: "flag flag-16 flag-tm",
    prefix: "+993",
    keyOnEnglish: "Turkmenistan",
    key: "Turkmenistán",
    code: "TM",
  },
  {
    class: "flag flag-16 flag-tr",
    prefix: "+90",
    keyOnEnglish: "Turkey",
    key: "Turquía",
    code: "TR",
  },
  {
    class: "flag flag-16 flag-tv",
    prefix: "+688",
    keyOnEnglish: "Tuvalu",
    key: "Tuvalu",
    code: "TV",
  },
  {
    class: "flag flag-16 flag-ua",
    prefix: "+380",
    keyOnEnglish: "Ukraine",
    key: "Ucrania",
    code: "UA",
  },
  {
    class: "flag flag-16 flag-ug",
    prefix: "+256",
    keyOnEnglish: "Uganda",
    key: "Uganda",
    code: "UG",
  },
  {
    class: "flag flag-16 flag-uy",
    prefix: "+598",
    keyOnEnglish: "Uruguay",
    key: "Uruguay",
    code: "UY",
  },
  {
    class: "flag flag-16 flag-uz",
    prefix: "+998",
    keyOnEnglish: "Uzbekistan",
    key: "Uzbekistán",
    code: "UZ",
  },
  {
    class: "flag flag-16 flag-vu",
    prefix: "+678",
    keyOnEnglish: "Vanuatu",
    key: "Vanuatu",
    code: "VU",
  },
  {
    class: "flag flag-16 flag-ve",
    prefix: "+58",
    keyOnEnglish: "Venezuela",
    key: "Venezuela",
    code: "VE",
  },
  {
    class: "flag flag-16 flag-vn",
    prefix: "+84",
    keyOnEnglish: "Vietnam",
    key: "Vietnam",
    code: "VN",
  },
  {
    class: "flag flag-16 flag-ye",
    prefix: "+967",
    keyOnEnglish: "Yemen",
    key: "Yemen",
    code: "YE",
  },
  {
    class: "flag flag-16 flag-dj",
    prefix: "+253",
    keyOnEnglish: "Djibouti",
    key: "Yibuti",
    code: "DJ",
  },
  {
    class: "flag flag-16 flag-zm",
    prefix: "+260",
    keyOnEnglish: "Zambia",
    key: "Zambia",
    code: "ZM",
  },
  {
    class: "flag flag-16 flag-zw",
    prefix: "+263",
    keyOnEnglish: "Zimbabwe",
    key: "Zimbabue",
    code: "ZW",
  },
];
